name: Playwright Test Workflow

on:
  push:
    branches:
      - project_ql

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build project
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # adding this steps to debug the correct path
      - name: List Playwright script path
        run: ls -R bin/

      - name: Install Playwright Browsers
        run: pwsh bin/Release/net8.0/playwright.ps1 install  # adjust net version
        
       # 👉 Add this step to run tests with xvfb (for headed mode)
      - name: Run Playwright Tests
        run: xvfb-run -a dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      # Upload artifacts
      - name: Upload test-logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            TestResults/
            Logs/ 
            Screenshots/
            bin/Debug/net8.0/playwright-report/

  download_artifacts:
    needs: build  # Ensure this job runs after the 'build' job
    runs-on: ubuntu-latest

    steps:
      # Download uploaded artifacts
      - name: Download test-logs artifact
        uses: actions/download-artifact@v4
        with:
          name: test-logs
          path: ./downloaded-artifacts
